### ISSUE TITLE
Submit Programma to Google Fonts

### ISSUE THREAD

**Issue by ayr-ton** [douglascrockford/Programma#2]
Can we submit Programma to https://github.com/google/fonts?

If @douglascrockford agrees, I would like to submit the font to the fonts directory of Google Fonts.

Also, provide some usages examples in the README.

Is this okay?

Thank you!

**Comment by douglascrockford** [comment]
I can't prevent it, but I would prefer if you wait a while. There may be some fixes that should be made before it googles.

**Comment by ayr-ton** [comment]
@douglascrockford Sure (:
I will wait for the fixes.

If you want you could reopen this issue later.
